
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: TerraformCLI@0
  inputs:
    command: 'init'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    backendType: 'azurerm'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'Terraorm-baendrg'
    backendAzureRmResourceGroupLocation: 'usa east'
    backendAzureRmStorageAccountName: 'aazibakaccounttrf'
    backendAzureRmContainerName: 'aazibakterr'
    backendAzureRmKey: 'k8saazibak'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
